# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mwin.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MWin(object):
    def setupUi(self, MWin):
        MWin.setObjectName("MWin")
        MWin.resize(720, 400)
        MWin.setMinimumSize(QtCore.QSize(720, 400))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        MWin.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/music-box.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MWin.setWindowIcon(icon)
        MWin.setIconSize(QtCore.QSize(40, 40))
        self.centralWidget = QtWidgets.QWidget(MWin)
        self.centralWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(5, 5, 0, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.type_Box = QtWidgets.QComboBox(self.tab)
        self.type_Box.setObjectName("type_Box")
        self.type_Box.addItem("")
        self.type_Box.addItem("")
        self.type_Box.addItem("")
        self.type_Box.addItem("")
        self.horizontalLayout.addWidget(self.type_Box)
        self.url_info = QtWidgets.QLineEdit(self.tab)
        self.url_info.setObjectName("url_info")
        self.horizontalLayout.addWidget(self.url_info)
        self.download_btn = QtWidgets.QToolButton(self.tab)
        self.download_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.download_btn.setObjectName("download_btn")
        self.horizontalLayout.addWidget(self.download_btn)
        self.open_download_fold_btn = QtWidgets.QToolButton(self.tab)
        self.open_download_fold_btn.setEnabled(True)
        self.open_download_fold_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_download_fold_btn.setObjectName("open_download_fold_btn")
        self.horizontalLayout.addWidget(self.open_download_fold_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.run_info = QtWidgets.QTextEdit(self.tab)
        self.run_info.setObjectName("run_info")
        self.verticalLayout_2.addWidget(self.run_info)
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(15, 11, 761, 341))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MWin.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MWin)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 720, 22))
        self.menuBar.setObjectName("menuBar")
        MWin.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MWin)
        self.statusBar.setObjectName("statusBar")
        MWin.setStatusBar(self.statusBar)

        self.retranslateUi(MWin)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MWin)

    def retranslateUi(self, MWin):
        _translate = QtCore.QCoreApplication.translate
        MWin.setWindowTitle(_translate("MWin", "Baidu Wenku Download v1.0.©LiKe"))
        self.type_Box.setItemText(0, _translate("MWin", "DOC"))
        self.type_Box.setItemText(1, _translate("MWin", "PPT"))
        self.type_Box.setItemText(2, _translate("MWin", "TXT"))
        self.type_Box.setItemText(3, _translate("MWin", "PDF"))
        self.url_info.setPlaceholderText(_translate("MWin", "在此输入链接地址，并选择正确的文件类型"))
        self.download_btn.setText(_translate("MWin", "Download"))
        self.download_btn.setShortcut(_translate("MWin", "Return"))
        self.open_download_fold_btn.setText(_translate("MWin", "Open Download Fold"))
        self.open_download_fold_btn.setShortcut(_translate("MWin", "Ctrl+Return"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MWin", "Home"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MWin", "Page"))
